### PR TITLE
Update test_gha.yml

### PR DESCRIPTION
**Pull request by vircadia-build-notifier**

### CODE REVIEW

**Comment by athena-build-notifier** [comment]
Test comment

**Comment by vircadia-build-notifier** [comment]
The following links are available: https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_9ef5fc34.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_9ef5fc34.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_9ef5fc34.dat

**Comment by vircadia-build-notifier** [comment]
The following links are available: https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_ed33b68c.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_ed33b68c.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_ed33b68c.dat

**Comment by vircadia-build-notifier** [comment]
The following links are available: https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_41c07a54.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_41c07a54.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_41c07a54.dat

**Comment by vircadia-build-notifier** [comment]
The following links are available: https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_d9062bdd.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_d9062bdd.dat, https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_d9062bdd.dat

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build_ubuntu**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_8e670d41.dat
**build_client_win32**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_8e670d41.dat
**build_osx**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_8e670d41.dat

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build_ubuntu**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/bump_a9042f03.txt
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_a9042f03.dat

**build_osx**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_a9042f03.dat
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/bump_a9042f03.txt

**build_client_win32**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/bump_a9042f03.txt
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_a9042f03.dat

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build_ubuntu**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/bump_3b3d359d.txt
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_3b3d359d.dat

**build_osx**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_3b3d359d.dat
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/bump_3b3d359d.txt

**build_client_win32**
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/bump_3b3d359d.txt
 - https://project-athena-builds.s3.eu-central-1.amazonaws.com/builds/PR/thoys_gha_test/PR2/temp_file_3b3d359d.dat

**Pull request merged**
